### ISSUE TITLE
error running on freshly update/upgrade rpi

### ISSUE THREAD

**Issue by terryhonn** [hachr/echo-home#1]
Hi, would like to see how this works, but after going thru your instructions, i get the following:
pi@raspberrypi ~/echo-home-js/echo-home $ node index
Username : ****************
Password : *********

events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at Echo.EventEmitter.emit (events.js:74:15)
    at Socket.<anonymous> (/home/pi/echo-home-js/echo-home/echo.js:68:8)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)

Anything I should try?

**Comment by hachr** [comment]
Looks like there were some error output from phantom js.  Can you pull down the latest and try again?  Btw, I renamed index.js to example.js

**Comment by hachr** [comment]
Finally got time to boot up my pi, it looks like you will need to build it for arm.  The error is:

<pre>phantomjs Syntax error: word unexpected (expecting ")")</pre>

You have a two options:
1. compile phantomjs for raspberry pi with the following instruction @ https://github.com/nowind/phantomjs-linux-armv7-sun4i/blob/master/README_armv6.md
2. use pre-built binary @ https://github.com/piksel/phantomjs-raspberrypi/ (Note: this is untrusted source and I am not sure how reliable this is.  Use this at your own discretion!)

Once you have the binary, copy it to echo-home/node_modules/phantomjs/bin/ and try again.
